// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rjtqnosvquzduhjsdzyt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJqdHFub3N2cXV6ZHVoanNkenl0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5NzE1MzMsImV4cCI6MjA2MzU0NzUzM30.VdbqPQQTNmD2_ENlyoQuZZkwCBuaXUkUjHw9TSomhCI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);